# Travis CI build configuration
#
# File must be verified with : http://lint.travis-ci.org/
#
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost1.50-all-dev
script:
  - mkdir bin && make && make -f MakefileInsert
