# Travis CI build configuration
#
# File must be verified with : http://lint.travis-ci.org/
#
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev libdb++-dev
script:
  - mkdir bin && make && make -f MakefileInsert
